[package]
name = "envizor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
sulphur-fs = { git = "https://github.com/Ounite/sulphur-fs.git" }

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
strip = true
